server:
  port: 9098
spring:
  data:
    mongodb:
      database: test
      host: 192.168.99.100
      port: 27017
eureka:
  instance:
    hostname: newsservice
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/
 userservice:
  url: http://192.168.99.100:9090       